server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://192.168.247.128:3307/apartment_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true&serverTimezone=UTC
    platform: mysql
    password: root
  redis:
    host: 192.168.247.128
  application:
    name: apartment-service
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.github.entropyfeng.apartment.domain.handler


logging:
  level:
    com.github.entropyfeng.apartment : info #打印sql